### ISSUE TITLE
[Unable to initialize x4driver_init in this Example]

### ISSUE THREAD

**Issue by Ash-S** [novelda/X4Driver_RaspberryPi_Example#1]
Hi, I set up well X4 interfaced with RPi3 according to this document.  I followed the guidelines step by step and compiled it well. while running ./Runme, I faced this result...Please suggest the solution. How can i see the streamed radar data?

**_raspbian_x4driver start to work!
task_radar start!
radar_hal_init success
x4driver_create success
task_radar_init success
x4driver_init unknown situation
x4driver_set_sweep_trigger_control success
Error setting dac minimum
Error code=-1
raspbian_x4driver done._**

**Comment by charlieshao5189** [comment]
The SPI communication seems not work. Please check your hardware connection.

**Comment by Ash-S** [comment]
Hi @charlieshao5189 , Thanks for your prompt reply! well, i prepared the connection like this, I rechecked. https://github.com/xethru/X4Driver_RaspberryPi_Example/blob/master/X4M05RPIconnection.pdf
Also enabled SPI at RPi3, but still same. Please suggest any other checks required. 

by the way, here in "radar_hal.h"   it defined like
#define X4_ENABLE_PIN 5
#define X4_GPIO_INT 6
#define SPI_CHANNEL 0

is that default OR do i need to change it since i am using:
PIN 14 as X4_ENABLE at X4M200;
PIN15 as X4_GPIO1 at X4M200;

Is that the reason?

**Comment by charlieshao5189** [comment]
You should keep the default pin assignment in radar_hal.h
Did you also check the quality of connection cables? Also, the pin map of the raspberry pi to avoid the wrong connection?
The following code is used to check SPI connection. I suspect this is the cause of "x4driver_init unknown situation".
``
    uint8_t force_one = 0x00;
    uint8_t force_zero = 0x00;
    x4driver_get_spi_register(x4driver, ADDR_SPI_FORCE_ONE_R, &force_one);
    x4driver_get_spi_register(x4driver, ADDR_SPI_FORCE_ZERO_R, &force_zero);
    if ((force_one != 0xff) || (force_zero != 0x00))
    {
        x4driver->initialized = 0;
        mutex_give(x4driver);
        return XEP_ERROR_X4DRIVER_NOK;
    }
``

**Comment by Ash-S** [comment]
Okay. But as i can see in the connection doc X4M05RPI connection.pdf; the PINs used at X4M05 header side are: 1,2,3,5,7,13,14,15 and defined pins in 'radar_hal.h' are 5 and 6. PIN6 (default) is not used in connection diagram. Can you please check that? Thanks!

**Comment by charlieshao5189** [comment]
This example uses a library called wiringPi, which has a different pin definition. See this page for detail:
http://wiringpi.com/pins/

**Comment by Ash-S** [comment]
yes I checked. Thanks.
Since its using wiringPi lib, the corresponding defined PINs are 5 and 6. That's correct!
But i didnt understand the cause of not initializing 'x4driver'. :(

**Comment by charlieshao5189** [comment]
Did you try to print out the force_one and force_zero printout?
If their values are not as expected, this is mostly a hardware connection problem according to my experience.

**Comment by Ash-S** [comment]
Yes, I checked it. force_one gives 255 and force_zero gives 255.  Seems, force_zero is not returning the expected value, It should give 0; but don't know why!!

**Comment by Ash-S** [comment]
When I power on the RPi first time (X4M200 is connected via SPI) and checked the force_one/force_zero registers, it shows:
FORCE_ZERO_REG = 0x0  (expected)
FORCE_ONE_REG = 0xFF (expected)
But still I see the message while running ./Runme: 'x4driver_init unknowne situation'
Please help!

**Comment by charlieshao5189** [comment]
Did you try to find which step the error happen? what's the return value?

**Comment by Ash-S** [comment]
Debug Result:
After power on board and first run ./Runme
force_zero: 0xff
force_one: 0xff AND then it shows error of "x4driver_init unknown situation"

After 2nd or 3rd run ./Runme works, it shows like..
force_zero: 0x00
force_one: 0xff
status = 0 (XEP_ERROR-X4DRIVER_OK)

But later again stucked at: 
_**raspbian_x4driver start to work!
task_radar start!
radar_hal_init success
x4driver_create success
task_radar_init success
x4driver_init success
x4driver_set_sweep_trigger_control success
x4driver_set_dac_min success
x4driver_set_dac_max success
x4driver_set_iterations success
x4driver_set_pulses_per_step success
**Error in x4driver_set_downconversion
Error code=20**
raspbian_x4driver done.**_

Seems, need to put some delay when initialize, Can you please check and suggest?

**Comment by charlieshao5189** [comment]
This program has been verified by many other users, so I don't think it is a software problem. Did you also try the X4M03, is it work as expected? Can you send a picture of your setup?

**Comment by Ash-S** [comment]
Yes, I tried with the X4M03 but the result is same...

_raspbian_x4driver start to work!
task_radar start!
radar_hal_init success
x4driver_create success
task_radar_init success

**forceZero: 0xFF
forceOne: 0xFF**

x4driver_init unknown situation
x4driver_set_sweep_trigger_control success
Error setting dac minimum
Error code=-1
raspbian_x4driver done._

![RPi-X4M03](https://user-images.githubusercontent.com/11657541/73900550-75ceae00-48d3-11ea-8793-92ee0a41edea.jpg)
![X4M03-RPi](https://user-images.githubusercontent.com/11657541/73900553-78310800-48d3-11ea-9b47-697316dbc421.jpg)

**Comment by charlieshao5189** [comment]
Hi AH-S,
You need to connect X4M05 instead of X4M03.
X4M05 = X4SIP02(X4 chip circuit)+X4A02(Antanna)
X4M03 = X4M05 + XTMCU02(MCU board for DSP)
By using X4M05 with RPI, you target to do radar singal DSP on RPI.

**Comment by Ash-S** [comment]
Okay. I'll test it and update you!

**Comment by Ash-S** [comment]
Hi @charlieshao5189 , i was preparing the connector adapter since X4M05 has 16pin small connector (1.27pitch). Anyway, i re-connected all the connection as mentioned in this example to both the sides (RPi <------>X4M05) and compiled and run it. Unfortunately same result. :(

_raspbian_x4driver start to work!
task_radar start!
radar_hal_init success
x4driver_create success
task_radar_init success
**forceZero: 0x00
forceOne: 0xFF**
x4driver_init unknown situation
x4driver_set_sweep_trigger_control success
Error setting dac minimum
Error code=-1
raspbian_x4driver done._

**Comment by charlieshao5189** [comment]
Can you send me a picture of your setup and the code you verify forceZero and forceOne?
To make sure this X4M05 still works well, could you run XeThru Explorer with X4M03(with this X4M05) to check if it still able to output radar raw data?

**Comment by Ash-S** [comment]
Yes, i do checked X4M03 with xep, works well. but since there is no uUSB in X4M05 i cant connect it directly. you mean with uart connection?
here is the setup RPi To X4M05:
![20200212_173434](https://user-images.githubusercontent.com/11657541/74317547-f81d0d80-4dbe-11ea-97b9-a49906a460a2.jpg)
![20200212_173321](https://user-images.githubusercontent.com/11657541/74317552-fa7f6780-4dbe-11ea-9f4f-4b8ff4f8ff44.jpg)

**Comment by charlieshao5189** [comment]
Hi Ash-S,
I do not find anything wrong with the connection and codes, but I have to suggestions for your debugging.
1. You mentioned the X4M03 and X4M05 report the same error and both passed force_one and force_zero. This is highly suspected because the X4M03 interface does not have an SPI port at all, so I suggest your redownload this repository to try. 

2. The connecter on X4M05 looks not so reliable, It would be better to check the connection between pin footprints on X4M05 and RPI pins.

**Comment by Ash-S** [comment]
Hi @charlieshao5189, i didnt understand the cause of getting this bug. for your information, i share here compile message using 'make' command: compiled well except 1 warning, could you please check is it the cause?

_OS: Linux
mkdir -p _build/src/XDriver
gcc -Wno-unused-variable -std=c11 -Iinclude/ -Isrc/XDriver/ -Isrc/Radar/ -Isrc/hal/  -MMD -MP -MT"_build/src/XDriver/x4driver.d" -MT"_build/src/XDriver/x4driver.o" -c src/XDriver/x4driver.c -o _build/src/XDriver/x4driver.o
src/XDriver/x4driver.c: In function ‘_update_downconversion_coeffs’:
src/XDriver/x4driver.c:320:16: **warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         {
                ^**
g++ _build/src/main.o _build/src/Radar/taskRadar.o _build/src/XDriver/x4driver.o _build/src/hal/radar_hal.o -o Runme  -lpthread -lwiringPi
echo "done"
done_

**Comment by charlieshao5189** [comment]
Hi @Ash-S ,
Glad to hear your good news!
Some useful pages for your development:
https://www.xethru.com/community/resources/categories/host-communication.32/ 
https://www.xethru.com/community/threads/welcome-to-the-xethru-community.410/
